#!/usr/bin/env node
/**
 * Renders the sitewide nav into every page and into the article template.
 *
 *   node scripts/build-nav.mjs           write the nav everywhere
 *   node scripts/build-nav.mjs --verify  fail if any page is out of date
 *
 * The nav was hand-written twice — once for the homepage, once for the blog
 * template — and drifted into two different components sharing a class name.
 * The logo was 44px on the homepage and 26px everywhere else, the bar was 80px
 * tall against 58px, and the links sat in different places because one used
 * `justify-content: space-between` and the other `gap` plus an auto margin. The
 * whole thing visibly jumped when you moved between pages.
 *
 * Same fix as the footer: define it once, render it everywhere, verify in CI.
 * The homepage design is the canonical one.
 */

import { readFileSync, writeFileSync, globSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const verifyOnly = process.argv.includes('--verify');

const KAJABI = 'https://www.onlinemodel.academy';
const PAID_OFFER = 'iJxLGaoD';

/** The links, in order. `anchor` ones only exist on the homepage. */
const LINKS = [
  { href: '#mentors', label: 'Mentors', anchor: true },
  { href: '#curriculum', label: 'Curriculum', anchor: true },
  { href: '#pricing', label: 'Pricing', anchor: true },
  { href: '#faq', label: 'FAQ', anchor: true },
  { href: 'blog/', label: 'Blog' },
];

// --- CSS --------------------------------------------------------------------
// Delimited by markers so repeated builds replace rather than append. Note the
// logo rules are scoped to `.nav` — the unscoped `.logo` they replaced also
// matched nothing else, but scoping keeps it that way on purpose.
const CSS_BEGIN = '/* nav:begin — generated by scripts/build-nav.mjs */';
const CSS_END = '/* nav:end */';

const CSS = `${CSS_BEGIN}
.nav { position: sticky; top: 0; z-index: 50; background: rgba(251,248,242,.82); backdrop-filter: blur(16px) saturate(1.3); -webkit-backdrop-filter: blur(16px) saturate(1.3); border-bottom: 1px solid transparent; transition: border-color .3s, background .3s; }
.nav.scrolled { border-bottom-color: var(--rule); }
.nav-in { max-width: 1280px; margin: 0 auto; padding: 18px 32px; display: flex; align-items: center; justify-content: space-between; }
.nav .logo { display: inline-flex; align-items: center; line-height: 0; }
.nav .logo img { height: 44px; width: auto; display: block; }
@media (min-width: 1200px) { .nav .logo img { height: 52px; } }
.nav-links { display: flex; gap: 32px; align-items: center; }
.nav-links a { text-decoration: none; font-size: 13px; font-weight: 500; color: var(--ink-soft); transition: color .2s; }
.nav-links a:hover, .nav-links a.on { color: var(--ink); }
.nav-right { display: flex; align-items: center; gap: 18px; }
.nav-login { font-size: 13px; font-weight: 500; color: var(--ink-soft); text-decoration: none; transition: color .2s; }
.nav-login:hover { color: var(--ink); }
.nav-cta { font-size: 13px; font-weight: 600; padding: 10px 20px; border-radius: 100px; background: var(--ink); color: var(--paper); text-decoration: none; transition: background .2s; }
.nav-cta:hover { background: var(--peach-dk); }
@media (max-width: 820px) { .nav-links { display: none; } .nav-cta { padding: 8px 16px; font-size: 12px; } .nav-right { gap: 12px; } .nav-login { font-size: 12px; } }
${CSS_END}`;

const esc = (s) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
const marked = new RegExp(`${esc(CSS_BEGIN)}[\\s\\S]*?${esc(CSS_END)}`, 'g');

/** The two hand-written nav CSS regions this replaces, one per original file. */
const HOMEPAGE_CSS = /\/\* ——— Nav ——— \*\/\n\.nav \{[\s\S]*?@media \(max-width: 820px\) \{[\s\S]*?\n\}/;
const ARTICLE_CSS = /\/\* Nav \*\/\n\.nav \{[\s\S]*?@media \(max-width:860px\)\{ \.nav-links\{display:none;\} \}/;

function applyCss(html) {
  if (marked.test(html)) {
    // Collapse any duplicates from an earlier non-idempotent run down to one.
    let first = true;
    return html.replace(marked, () => (first ? ((first = false), CSS) : ''));
  }
  if (HOMEPAGE_CSS.test(html)) {
    // `.ft .logo img` sat inside this region and is dead: the footer's image
    // carries no `.logo` class and an inline height that would win anyway.
    return html.replace(HOMEPAGE_CSS, CSS);
  }
  if (ARTICLE_CSS.test(html)) return html.replace(ARTICLE_CSS, CSS);
  return html;
}

// --- markup -----------------------------------------------------------------
const MARKUP_BEGIN = '<!-- nav:begin — generated by scripts/build-nav.mjs -->';
const MARKUP_END = '<!-- nav:end -->';

/**
 * The border only appears once the page has scrolled, which needs a listener.
 * It used to live in the homepage's main script, so moving this nav onto the
 * blog would have shipped a border that never appeared. It travels with the
 * markup instead.
 */
const SCRIPT =
  `<script>(function(){var n=document.getElementById('nav');if(!n)return;` +
  `var f=function(){n.classList.toggle('scrolled',window.scrollY>8);};` +
  `f();window.addEventListener('scroll',f,{passive:true});})();</script>`;

function nav({ prefix, home, logoHref, isBlog, ctaHref, ctaAttrs }) {
  const links = LINKS.map((l) => {
    const href = l.anchor ? `${home}${l.href}` : `${prefix}${l.href}`;
    const on = !l.anchor && isBlog ? ' class="on"' : '';
    return `\n      <a${on} href="${href}">${l.label}</a>`;
  }).join('');

  return `${MARKUP_BEGIN}
<nav class="nav" id="nav">
  <div class="nav-in">
    <a class="logo" href="${logoHref}" aria-label="Online Model Academy"><img src="${prefix}assets/logo-black.svg" alt="Online Model Academy"></a>
    <div class="nav-links">${links}
    </div>
    <div class="nav-right">
      <a class="nav-login" href="${KAJABI}/login" target="_blank" rel="noopener">Log in</a>
      <a class="nav-cta"${ctaAttrs} href="${ctaHref}" target="_blank" rel="noopener">Enrol — $299</a>
    </div>
  </div>
</nav>
${SCRIPT}
${MARKUP_END}`;
}

const markedMarkup = new RegExp(`${esc(MARKUP_BEGIN)}[\\s\\S]*?${esc(MARKUP_END)}`);
const rawNav = /<nav class="nav"[^>]*>[\s\S]*?<\/nav>/;

const targets = globSync('**/*.html', { cwd: ROOT }).filter(
  (p) => !['node_modules/', 'project/'].some((d) => p.startsWith(d)),
);

const problems = [];
let written = 0;

for (const page of targets) {
  const file = join(ROOT, page);
  const original = readFileSync(file, 'utf8');

  const isTemplate = page === 'content/article-template.html';
  const depth = isTemplate ? 2 : dirname(page).split('/').filter((s) => s !== '.').length;
  const prefix = '../'.repeat(depth);
  const home = depth === 0 ? '' : `${prefix}index.html`;
  const logoHref = depth === 0 ? '#' : `${prefix}index.html`;

  const slug = isTemplate
    ? '{{SLUG}}'
    : page === 'blog/index.html'
      ? 'blog-index'
      : (page.match(/^blog\/([^/]+)\/index\.html$/)?.[1] ?? null);

  // The homepage nav CTA deliberately carries no UTMs, matching how its other
  // CTAs are tagged; every other page keeps its own utm_content so nav enrols
  // stay attributable to the article that drove them.
  const ctaHref = slug
    ? `${KAJABI}/offers/${PAID_OFFER}?utm_source=blog&utm_medium=article&utm_campaign=enrol_299&utm_content=${slug}__nav`
    : `${KAJABI}/offers/${PAID_OFFER}`;
  const ctaAttrs = slug ? ' data-cta="nav-enrol"' : '';

  const rendered = nav({ prefix, home, logoHref, isBlog: slug !== null, ctaHref, ctaAttrs });

  let updated = markedMarkup.test(original)
    ? original.replace(markedMarkup, rendered)
    : original.replace(rawNav, rendered);

  updated = applyCss(updated);

  // The homepage's own scroll handler is now redundant — the nav ships its own.
  updated = updated.replace(
    /\n  \/\* Nav scrolled \*\/\n  const nav = \$\('#nav'\);\n  window\.addEventListener\('scroll', \(\) => \{\n    nav\.classList\.toggle\('scrolled', window\.scrollY > 8\);\n  \}, \{ passive: true \}\);\n/,
    '\n',
  );

  if (updated === original) continue;

  if (verifyOnly) {
    problems.push(`${page}: nav is out of date — run \`npm run build:nav\`.`);
  } else {
    writeFileSync(file, updated);
    written += 1;
  }
}

if (verifyOnly) {
  if (problems.length) {
    console.error(`build-nav: ${problems.length} problem(s):\n`);
    for (const p of problems) console.error(`  ✗ ${p}`);
    process.exit(1);
  }
  console.log(`build-nav: nav is current across ${targets.length} files.`);
  process.exit(0);
}

console.log(`build-nav: updated ${written} of ${targets.length} files.`);
